"""
PDF Report Generator
"""

from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)


def create_report(filename, title, data):
    """
    Generate a professional PDF report.
    """

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    heading = styles["Heading1"]
    heading.alignment = TA_CENTER

    elements = []

    # Title
    elements.append(
        Paragraph(title, heading)
    )

    elements.append(
        Spacer(1, 12)
    )

    # Generated Date
    elements.append(
        Paragraph(
            f"<b>Generated:</b> {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            styles["Normal"]
        )
    )

    elements.append(
        Spacer(1, 12)
    )

    # Table Data
    table_data = [["Field", "Value"]]

    for key, value in data.items():

        table_data.append(
            [str(key), str(value)]
        )

    table = Table(
        table_data,
        colWidths=[170, 280]
    )

    table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkgreen),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),

            ("ALIGN", (0, 0), (-1, -1), "CENTER")

        ])

    )

    elements.append(table)

    elements.append(
        Spacer(1, 20)
    )

    elements.append(

        Paragraph(

            "<b>Generated by AI Crop Advisory System</b>",

            styles["Normal"]

        )

    )

    doc.build(elements)